# Generated by Django 4.0.1 on 2022-01-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPIapp', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='john doe', max_length=150),
        ),
    ]
